name: CI

on: [push]

jobs:
  standard-checks:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install packages
        run: npm ci
        working-directory: ./BackEnd

      - name: Start the server
        run: |
          npm run build
          npm start
          curl http://localhost:3000
          sleep 10s
          kill $(cat /tmp/pidfile)
        working-directory: ./BackEnd
        run: sleep 10s
        run: kill $(cat /tmp/pidfile)
        if: always()
